apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapiseguridad
spec:
  selector:
    matchLabels:
      app: testapiseguridad
  replicas: 2
  template:
    metadata:
      labels:
        app: testapiseguridad
    spec:
      containers:
      - name: testapiseguridad
        image: aaronma/testapiseguridad:latest
        imagePullPolicy: Always        
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: testapiseguridad
  labels:
    app: testapiseguridad
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http-traffic
  selector:
    app: testapiseguridad
  type: LoadBalancer
