apiVersion: apps/v1
kind: Deployment
metadata:
  name: testproxyreverso
spec:
  selector:
    matchLabels:
      app: testproxyreverso
  replicas: 1
  template:
    metadata:
      labels:
        app: testproxyreverso
    spec:
      containers:
      - name: testproxyreverso
        image: aaronma/testproxyreverso:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: testproxyreverso
  labels:
    app: testproxyreverso
spec:
  ports:
    - port: 8095
      protocol: TCP
      targetPort: 8085
      name: http-traffic
  selector:
    app: testproxyreverso
  type: LoadBalancer